Kevin Pho dev teams pages fixes
SSWConsulting/zzSSW.Website pull request #154
Opened 2022-04-22 07:13 UTC by kevinpho2022

https://github.com/SSWConsulting/SSW.Website.Content/issues/19

Added required props for enabling changes made in SSW.Website.content
Added props to react template
Added conditional to handle if there's nothing in the technology list

2022-04-26 01:09 UTC, lukecookssw requested changes
Please see changes noted.

2022-04-26 01:09 UTC, lukecookssw commented on src/styles/global.css
> +    color:white;
Move this styling out of global.css and into the component's specific CSS file. We don't want it to apply to every anchor tag across the entire website.

2022-04-26 01:09 UTC, lukecookssw commented on src/templates/consulting/components/benefits/index.tsx
> +                                    {' '}
Remove this hard-coded space and instead use CSS styling such as margin-left on the anchor tag.

2022-04-26 01:09 UTC, lukecookssw commented on src/templates/consulting/components/technologies/index.tsx
> +        }
Is the else statement required? I don't think it is.

2022-04-26 01:09 UTC, lukecookssw commented on src/templates/consulting/components/technologies/index.tsx
> +
Remove the else statement and instead do:

if (techList &&)

(the syntax above is pseudo-code, but pretty close. There's a weird thing in React where it forces you to put an else statement _unless_ you use this && operator.

2022-04-26 06:16 UTC, kevinpho2022 commented on src/templates/consulting/components/benefits/index.tsx
> +                                    {' '}
used margin-left as recommended

2022-04-26 06:16 UTC, kevinpho2022 commented on src/styles/global.css
> +    color:white;
moved into component specific css file

2022-04-26 06:16 UTC, kevinpho2022 commented on src/templates/consulting/components/technologies/index.tsx
> +        }
removed

2022-04-26 06:23 UTC, kevinpho2022 commented on src/templates/consulting/components/technologies/index.tsx
> +
removed the else clause

2022-05-13 00:14 UTC, lukecookssw approved these changes
LGTM

2022-05-13 00:14 UTC, merged